// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcm0n1ebfOXJRTG9a2DL455_dtG902Dn4',
    appId: '1:907148332995:web:fe68f52c8c595a4adc3776',
    messagingSenderId: '907148332995',
    projectId: 'exelynt-learning',
    authDomain: 'exelynt-learning.firebaseapp.com',
    storageBucket: 'exelynt-learning.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1382nBCK8-K2rBOJ8DnO7snR5yM7R9u0',
    appId: '1:907148332995:android:ef7ae8d95c04d6d9dc3776',
    messagingSenderId: '907148332995',
    projectId: 'exelynt-learning',
    storageBucket: 'exelynt-learning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLrPQSiOoYo8V_Ex8BDiGMEGbcIp6uK5w',
    appId: '1:907148332995:ios:8bd66effe837d47bdc3776',
    messagingSenderId: '907148332995',
    projectId: 'exelynt-learning',
    storageBucket: 'exelynt-learning.firebasestorage.app',
    iosBundleId: 'com.example.exelyntLearning',
  );
}
